### ISSUE TITLE
How to view traces after the first one?

### ISSUE THREAD

**Issue by alexmojaki** [laike9m/Cyberbrain#49]
I tried out the demo on Gitpod and followed the instructions. After viewing the first example I ran a different example but didn't know how to view the graph. Eventually I figured out that killing the first process with Ctrl+C made it possible to reinitialize Cyberbrain with a new example. Is this the best way? If so, consider adding it to the instructions.

**Comment by laike9m** [comment]
This is definitely something I need to improve. Right now the server listens on a hard-coded port, and UI talks to that port. If you have a better idea for how to make it work better, let me know. The only solution I can think of right now is to dump the mapping (port -> program being debugged) to a file, but I don't really like this approach since it brings in an extra outer dependency which is the file system.

**Comment by laike9m** [comment]
Actually, I think I can add a new API endpoint for discovering the currently running program. It should not be too hard.

**Comment by alexmojaki** [comment]
I don't know how the system works right now, but I imagine you could have multiple running programs all communicating with the UI so that the UI can show a selection of different running programs.

A completely different approach would be that running a traced program both immediately starts a server on a random port and opens the webbrowser in that port.

Either way, document the best available workaround in the docs for now while you come up with a solution. As I said, this stumped me for a bit when I tried the demo.

**Comment by laike9m** [comment]
OK will do 😂

**Comment by laike9m** [comment]
I closed this issue cause it's more related to documentation. Will have separate issue(s) for optimizing the use case.
