### ISSUE TITLE
ImportError: No module named cyberbrain

### ISSUE THREAD

**Issue by zealot-shin** [laike9m/Cyberbrain#91]
**Describe the bug**
after installed cyberbrain in vscode, i wrote following line in my python file

from cyberbrain import trace

but when i tried running without debugging, following error occurred:
ImportError: No module named cyberbrain

It seems that cyberbrain is not enabled in my workspace.but from vscode extensions view I can see this extension is enabled.

I tried installing cyberbrain by pip install, but couldnot find the repo:
ERROR: Could not find a version that satisfies the requirement cyberbrain (from versions: none)
ERROR: No matching distribution found for cyberbrain

**Code to reproduce the bug**
Please provide a code snippet that can reproduce the bug
```python
from cyberbrain import trace

class Obj(object):

    @trace
    def method(self):
        ...
```

**Screenshots and/or error messages**
![image](https://user-images.githubusercontent.com/12884162/108456145-94b79c80-72aa-11eb-9bfa-52d978bec8aa.png)

If you see any error message, please also paste it here.

**Environment:**
Please provide the following information:
- OS you're using Linux ubuntu 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Python version 2.7.17
- Cyberbrain Python lib version -
- Cyberbrain VS Code extension version 0.1.3

**Comment by laike9m** [comment]
Unfortunately Cyberbrain only supports Python 3.7+:
![image](https://user-images.githubusercontent.com/2592205/108456287-d6056900-7224-11eb-86ee-7164cb6557cc.png)

The error you described means that pip is not able to install cyberbrain because it does not support the Python version you're using (2.7)
> I tried installing cyberbrain by pip install, but couldnot find the repo:
ERROR: Could not find a version that satisfies the requirement cyberbrain (from versions: none)
ERROR: No matching distribution found for cyberbrain
